apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: default
  labels:
    k8s-app: testapp
spec:
  replicas: 3
  selector:
    matchLabels:
      k8s-app: testapp
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        k8s-app: testapp
    spec:
      containers:
        - name: testapp
          image: quay.io/coreos/example-app:v1.0
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
           httpGet:
             path: /books
             port: 8080
             scheme: HTTP
          livenessProbe:
           initialDelaySeconds: 30
           timeoutSeconds: 1
           httpGet:
             path: /books
             port: 8080
             scheme: HTTP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
