apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: default
  labels:
    k8s-app: testapp
spec:
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      k8s-app: testapp
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        k8s-app: testapp
    spec:
      containers:
        - name: testapp
          image: renatocardoso.azurecr.io/springtest:v1.0
          env:
          - name: AZURE_MONGO_DB
            valueFrom:
              secretKeyRef:
                name: cosmosdb-connection-string
                key: connection-string
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
           httpGet:
             path: /books
             port: 8080
             scheme: HTTP
          livenessProbe:
           initialDelaySeconds: 30
           timeoutSeconds: 1
           httpGet:
             path: /books
             port: 8080
             scheme: HTTP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
