name: Deploy Spring Boot App as Docker Container to AKS cluster
on: [deployment]
jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile Maven project
    steps:
      - uses: actions/checkout@master
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - run: mvn -f pom.xml compile
  build:
    runs-on: ubuntu-latest
    needs: compile
    name: Build Maven project
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      env:
        AZURE_MONGO_DB: ${{ secrets.AZURE_MONGO_DB }}
      run: mvn -f pom.xml install
    - name: Upload Maven build artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifact
        path: target/myJar.jar
  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Build Docker container and deploy to Kubernetes
    steps:
      - uses: actions/checkout@v1
      - name: Download Maven build artifact
        uses: actions/download-artifact@v1
        with:
          name: artifact
      - name: Copy .jar to default path
        run: |
          mkdir target
          cp artifact/myJar.jar target/mongo-cosmodb-test.jar
      - name: Login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.AZURE_CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.AZURE_CONTAINER_REGISTRY_PASSWORD }}
      - name: Build and Push Docker image to ACR
        run: |
          docker build --build-arg AZURE_MONGO_DB="${{ secrets.AZURE_MONGO_DB }}" -t ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/springtest:${{ github.sha }} .
          docker push ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/springtest:${{ github.sha }}
      - name: Configure AKS context
        uses: azure/aks-set-context@v1
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: testcluster
          resource-group: testspring
      - name: Deploy rolling update to AKS cluster
        uses: Azure/k8s-deploy@v1
        with:
          manifests: |
            manifests/deployment.yml
            manifests/service.yml
          images: |
            ${{ secrets.AZURE_CONTAINER_REGISTRY_LOGIN_SERVER }}/springtest:${{ github.sha }}
